language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hashbug/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hashbug/docker-react npm run test -- --coverage
